# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.10.2
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: mysql:5.7
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --innodb-large-prefix=true --innodb-file-format=Barracuda
        environment:
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: true
        ports:
          - 3306:3306

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/hauxe/GoM
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run:
          name: get mysql client
          command: sudo apt install -y mysql-client
      - run:
          name: create mysql default database
          command: mysql  -h 127.0.0.1 -u root -e "CREATE SCHEMA IF NOT EXISTS default_db DEFAULT CHARACTER SET utf8;"
      - run:
          name: create mysql default user
          command: mysql  -h 127.0.0.1 -u root -e "CREATE USER IF NOT EXISTS 'username' IDENTIFIED BY 'password';"
      - run:
          name: grant mysql permission
          command: mysql  -h 127.0.0.1 -u root -e "GRANT ALL ON default_db.* TO 'username';"
      - run: go get -u github.com/golang/dep/cmd/dep
      - run: dep ensure
      - run: go test -v -race ./...